In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
data=pd.read_csv("spam.csv")

In [3]:
data.head()

Label                                          EmailText
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
data.groupby('Label').describe()

EmailText                                                               
          count unique                                                top freq
Label                                                                         
ham        4825   4516                             Sorry, I'll call later   30
spam        747    653  Please call our customer service representativ...    4

In [6]:
data['Spam']=data['Label'].apply(lambda x:1 if x=='spam' else 0)
data.head()

Label                                          EmailText  Spam
0   ham  Go until jurong point, crazy.. Available only ...     0
1   ham                      Ok lar... Joking wif u oni...     0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3   ham  U dun say so early hor... U c already then say...     0
4   ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
X_train,X_test,y_train,y_test=train_test_split(data.EmailText,data.Spam,test_size=0.25)

In [13]:
X_train.values

array(['Tomorrow i am not going to theatre. . . So i can come wherever u call me. . . Tell me where and when to come tomorrow',
       'There are some nice pubs near here or there is Frankie n Bennys near the warner cinema?',
       'It just seems like weird timing that the night that all you and g want is for me to come smoke is the same day as when a shitstorm is attributed to me always coming over and making everyone smoke',
       ...,
       'Congrats! Nokia 3650 video camera phone is your Call 09066382422 Calls cost 150ppm Ave call 3mins vary from mobiles 16+ Close 300603 post BCM4284 Ldn WC1N3XX',
       'Is xy going 4 e lunch?', 'I am in your office na.'], dtype=object)

In [21]:
y_test.values

array([1, 0, 0, ..., 0, 0, 1], dtype=int64)

In [11]:
len(X_test)

1393

In [17]:
v=CountVectorizer()

In [18]:
X_train_new=v.fit_transform(X_train.values)
X_train_new.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
model=MultinomialNB()

In [22]:
model.fit(X_train_new,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [23]:
emails=[
    'hey,mohan ,can we get together to watch football game tomorrow? ',
    'Upto 20% discount on parking ,exclusive offer just for you ,Dont miss this !'
]

In [24]:
email_count=v.transform(emails)
model.predict(email_count)
#here you can see the 1 email is not spam and 2 is spam and our model predict perfect!!

array([0, 1], dtype=int64)

In [25]:
X_train_new=v.transform(X_test)
model.score(X_train_new,y_test)

0.9877961234745154